### ISSUE TITLE
[content] breadcrumb text

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/airlessco#112]
Need some titles added in some cases, and some products are ALL CAPS in Franklin (but not the live site).
![2023-02-08_10-52-25](https://user-images.githubusercontent.com/3883795/217581891-b4dd29e5-195f-48df-9edf-3e70ca531ef0.png)

Live site: https://www.airlessco.com/emea/es/products/accessories/revtipspraytips/
Franklin: https://main--airlessco--hlxsites.hlx.page/emea/de/products/accessories/revtipspraytips

**Comment by bstopp** [comment]
To fix `accessoriesNavLabel` add an entry in the placeholders per language with the appropriate value.

To fix the header being in title case, Change the title on the page to the desired case state OR add a `Nav Title` entry in the MetaData table at the end of the content source, with the desired value for the Breadcrumb

**Comment by bstopp** [comment]
This was fixed via content edits.
