### ISSUE TITLE
Accessories page cards don't link

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/airlessco#119]
The cards on the accessories listing pages (such as /na/en/products/accessories/) should be linked, not just the text.

**Comment by bstopp** [comment]
Can you also take a look at the sizes on mobile:

Left is live, right is current main:

<img width="747" alt="Airlessco_Airless_Spray_Guns___Airlessco_com_and_Airlessco_Airless_Spray_Guns___Airlessco_com" src="https://user-images.githubusercontent.com/6520270/218506159-bf6bc0a4-abdb-4739-96ce-dc7cfab76e4c.png">

**Comment by helms-charity** [comment]
@bstopp what page is this? It's not the main page scoped to this ticket. My local looks like the left one. Was there a recent change that broke the part you are seeing?
![image](https://user-images.githubusercontent.com/3883795/218555051-d47a7bc4-430a-4039-8619-1742603d0bc1.png)
