### ISSUE TITLE
Add Image metadata to all pages.

### ISSUE THREAD

**Issue by bstopp** [hlxsites/airlessco#128]

**Comment by helms-charity** [comment]
From Bryan:
"every product page should have the first image in the carousel as a metadata entry, that way it shows up correctly in the index and on the header of the document"
https://docs.google.com/document/d/1Q0_aUnppLQyflSgPZnihMa7eaGX1_16g2SlDgnzsrUc/edit#

**Comment by bstopp** [comment]
Feel free to close this once it's done.

**Comment by helms-charity** [comment]
I did all Product pages in all locales, were there other pages to look at? Maybe accessories?

**Comment by bstopp** [comment]
Accessories will be done by import

**Comment by helms-charity** [comment]
OK, closing.
