### ISSUE TITLE
Accessories Labels Not Rent

### ISSUE THREAD

**Issue by lamontacrook** [hlxsites/airlessco#139]
Example Page:
https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/

![image](https://user-images.githubusercontent.com/2071728/220396333-a0ec0335-682f-429e-8897-776d5ccc4e39.png)

**Comment by bstopp** [comment]
This is a content issue - need the Nav Title in the page's metadata.

**Comment by helms-charity** [comment]
All fixed.
