### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by angellg1** [hlxsites/airlessco#148]
Please add the Google tag manager script in the head of all pages - 

`

--
  | <script>(function(w,d,s,l,i){w[l]=w[l]\|\|[];w[l].push({'gtm.start':
  | new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  | j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  | 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  | })(window,document,'script','dataLayer','GTM-WZ7D96C');</script>
  | 

`

Also add this after the opening body tag:

--
  | <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WZ7D96C"
  | height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  | 

`

**Comment by lamontacrook** [comment]
I will take this.

**Comment by bstopp** [comment]
Do we need the iframe bit? If there's no JavaScript, the site won't render content at all.

**Comment by angellg1** [comment]
The noscript tag is only to track users when their browser disables javascript. I have never not included it so I can't say its fine without it, but we can test it without it to see if all is good.

**Comment by bstopp** [comment]
This should be on the preview/live site now. Please confirm and re-open if there are issues. (not the no-script tag though).
