### ISSUE TITLE
Content missing or in error for Accessories pages

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/airlessco#150]
General CSS fixes are needed (bold, font size, some spacing, etc), but I will list what I think are content fixes here.
1. https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/sprayguns
- Missing the links to the repair manuals, 
- "Airless spray guns" should not appear in the "more accessories" section.

2. https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/revtipspraytips
- Table font should be 16, not 13 (will put this on the CSS issue)
- "Rev tip spray guns" should not appear in the "more" section

3. https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/hoses
- "airless hoses' should not appear in the "more" section

4. https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/extensions
-  Bryan already separated the 1 table into 2, but now there is a large gap. Need to fix the other languages for this product, the 2nd table's heading is missing and the tables are conjoined there.
- Need to fix the table header font size, color, and weight -- this accessory is different than the others.

5. https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/fluids
- The first table needs to be separated into 2 so that MagiCLEAN CONCENTRATE is not missing,
- The links and icons to the PDFs are missing
- "Fluids" should not appear in the "more' section

6. https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/filters
- 1st two itens, Prolight 500 gun filters and Manifold filters are both missing part numbers.
- "filters" should not appear in the "More" section

7. https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/striping
- GRAVITY FEED GLASS BEAD DISPENSER missing a part number
- "striping' should not appear in the 'More" section
- SURE STRIPE TIPS is missing the Tip Size Chart

8. https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/other
- Replacement Pumps, GUN & HOSE CONNECTORS, Hose Cover sections are missing part numbers
- "other" should not appear in the "More" list

**Comment by helms-charity** [comment]
http://localhost:3000/na/en/products/accessories/revtipspraytips needs "TIP SIZE CHART:" bolded in content. The rest I'm getting with CSS.

**Comment by helms-charity** [comment]
https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/revtipspraytips is missing "Fluids' and "filters" in the "more accessories" section.

**Comment by lamontacrook** [comment]
Finished content updates to `na/en`

**Comment by lamontacrook** [comment]
Finished content update to emea/en

**Comment by bstopp** [comment]
These are all fixed with the new import.
