### ISSUE TITLE
Accessories CSS issues

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/airlessco#151]
https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/revtipspraytips
Table font should be 16, not 13 

all pages:
PART NUMBER:, DESCRIPTION:, AVAILABILITY: table row headers should all be bolded.

The accessory section headings font shuold be 16px #777 and font-weight: 400. when Strong is used in the content, then it should be 24px, black, and 700. Should not be forced uppercase.

MORE ACCESSORIES heading should be black

**Comment by lamontacrook** [comment]
I'm bolding the PART NUMBER, etc
