### ISSUE TITLE
More Accessories Fluids pulling the wrong thumbnail

### ISSUE THREAD

**Issue by lamontacrook** [hlxsites/airlessco#153]
![image](https://user-images.githubusercontent.com/2071728/220714038-5d3b3bd2-1fda-4442-8a45-a61b3b982c58.png)

My guess is that the block is pulling the first image but on fluids page its the second.

**Comment by helms-charity** [comment]
Fixed 
https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/
