### ISSUE TITLE
All Caps and "Normal Text" in Accessories Details need to be fixed

### ISSUE THREAD

**Issue by lamontacrook** [hlxsites/airlessco#154]
Preview:

![image](https://user-images.githubusercontent.com/2071728/220716223-cdd7aa2b-9a7d-4fa2-9f56-0caab0cb1f48.png)

Live:

![image](https://user-images.githubusercontent.com/2071728/220716453-c4877937-dc0c-4bff-95e0-067a44d3515c.png)

**Comment by bstopp** [comment]
Fixed with new import.
