### ISSUE TITLE
Accessories Details Image Needs to have option Span 2 Sections

### ISSUE THREAD

**Issue by lamontacrook** [hlxsites/airlessco#155]
Preview:

![image](https://user-images.githubusercontent.com/2071728/220717271-d9009175-e925-4b11-9aac-3a2880510f55.png)

Live:

![image](https://user-images.githubusercontent.com/2071728/220717461-f0c53aac-6fad-446f-a8e9-4fec94308fc9.png)

**Comment by bstopp** [comment]
Closing this, won't fix as the change makes things consistent on all author context, rather than trying to customize each individual pages.
