### ISSUE TITLE
Check CSS for accessories tables

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/airlessco#158]
post import, Bryan says there are some CSS fixes needed for tables, especially in mobile.
example:
https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/revtipspraytips

**Comment by helms-charity** [comment]
![image](https://user-images.githubusercontent.com/3883795/221022371-821e1591-111e-4311-bd32-be341d8cd692.png)
Our footer on left is too big.

**Comment by helms-charity** [comment]
Line height on the section title (live is on right) 
![image](https://user-images.githubusercontent.com/3883795/221023927-b53f3472-f0fc-430f-b8cc-e191db0c246b.png)

**Comment by helms-charity** [comment]
consider removing min-widths for mobile tables 
![image](https://user-images.githubusercontent.com/3883795/221025107-ee1bc801-67c5-4055-b05c-bd4fa8f8a357.png)

**Comment by helms-charity** [comment]
Width and H1 style needs fixing for product landing pages 
![image](https://user-images.githubusercontent.com/3883795/221033791-8d2fc5c2-3f08-463b-a355-20f8eb6d47ee.png)

**Comment by helms-charity** [comment]
Grey 'super title' disappears unexpectedly in sizes less than 768px
(also "de" should be lowecase)
![image](https://user-images.githubusercontent.com/3883795/221036534-5b1cb63e-4bc7-4b18-a075-0d6a3b7ebea0.png)

**Comment by bstopp** [comment]
> Grey 'super title' disappears unexpectedly in sizes less than 768px (also "de" should be lowecase) ![image](https://user-images.githubusercontent.com/3883795/221036534-5b1cb63e-4bc7-4b18-a075-0d6a3b7ebea0.png)

This disappears on all the other languages because it comes _after_ the Bold part. I wouldn't change this tbh.

**Comment by bstopp** [comment]
> Width and H1 style needs fixing for product landing pages ![image](https://user-images.githubusercontent.com/3883795/221033791-8d2fc5c2-3f08-463b-a355-20f8eb6d47ee.png)

I fixed this via Author change.

**Comment by helms-charity** [comment]
I think we need to break-word in the H1
![image](https://user-images.githubusercontent.com/3883795/221038476-0f8c5b73-12ce-401a-9f9f-6b3e5122a243.png)

**Comment by helms-charity** [comment]
Content problems for /emea/nl/products/hv3000comfort
Also need to set a different height on the image for mobile.
![image](https://user-images.githubusercontent.com/3883795/221039249-312a2aa6-d26b-4220-9c4b-9548fdd50b5f.png)

**Comment by bstopp** [comment]
> I think we need to break-word in the H1 ![image](https://user-images.githubusercontent.com/3883795/221038476-0f8c5b73-12ce-401a-9f9f-6b3e5122a243.png)

This is the same as live site, I wouldn't stress about it. 
<img width="323" alt="Airlessco_Verfspuittoestellen___Airlessco_com" src="https://user-images.githubusercontent.com/6520270/221040801-93ee5219-75f0-4903-bb29-419f46a531c4.png">

**Comment by helms-charity** [comment]
More content fixes needed
https://main--airlessco--hlxsites.hlx.page/emea/nl/products/ss3350
![image](https://user-images.githubusercontent.com/3883795/221041923-fdf16832-c278-4604-bb65-8c177d178a3c.png)

**Comment by bstopp** [comment]
> More content fixes needed https://main--airlessco--hlxsites.hlx.page/emea/nl/products/ss3350 ![image](https://user-images.githubusercontent.com/3883795/221041923-fdf16832-c278-4604-bb65-8c177d178a3c.png)

This was intentional - the bullets anyway.

Fixed the Accessories section via content edit.

Won't fix the order of the wording on the mobile view for product specifications - as it would be a more one-off and different than every other product page.

**Comment by bstopp** [comment]
> Content problems for /emea/nl/products/hv3000comfort Also need to set a different height on the image for mobile. ![image](https://user-images.githubusercontent.com/3883795/221039249-312a2aa6-d26b-4220-9c4b-9548fdd50b5f.png)

Not going to fix this - the Description word comes from the placeholders, and making it unique to this product line would be a one-off solution. More complexity for Authors than needed

**Comment by helms-charity** [comment]
Things I fixed
- Fixed the incorrect "compare to" product on  https://main--airlessco--hlxsites.hlx.page/emea/nl/products/sp380
- Did not change the "compare to" order on the other products because I think having the 1st item being the current product makes the most sense. The way we have it is more consistent.
- Swapped product image order for all languages for /products/hss9950gas and for /products/lp955.
- Did not change the nav-title for the HVLP accessory shown on https://main--airlessco--hlxsites.hlx.page/emea/cz/products/hv3000comfort, so it doesn't match the live site, but it is consistent with the naming of it on it's own page.
- relaxed fontawesome PDF icon application strictness in CSS because sometimes the links are wrapped in <p>. Example: https://main--airlessco--hlxsites.hlx.page/emea/cz/products/lp555. Note we have more space between our links due to an added <br> on many pages, but not all.
- Changed out wrong product image for /products/ss3350, /products/ss4350 and /products/ss3350sp for all languages where applicable.
- Changed the column heading on product spreadsheet to say "Description", and fixed missing descriptions on all CZ product pages


Things to be looked at
- TO CHECK: We are setting uppercase on the product title with CSS, but there are many non-uppercase words on the live site pages. Example https://main--airlessco--hlxsites.hlx.page/emea/de/products/hv4000luxe 
- TO CHECK: Live site only has 2 items in the "compare to" for this product in all languages, Ours has 3 https://main--airlessco--hlxsites.hlx.page/emea/nl/products/ts1750
- TO CHECK: This product image doesn't have a hose in it on the live site for any language except English - https://main--airlessco--hlxsites.hlx.page/emea/cz/products/hss9950electric
- TO DO: add missing 2nd image for https://main--airlessco--hlxsites.hlx.page/emea/nl/products/ss4350, but I couldn't figure out where to add it in GDrive.
