### ISSUE TITLE
Product Titles are forced uppercase.

### ISSUE THREAD

**Issue by bstopp** [hlxsites/airlessco#160]
Concern: 

> We are setting uppercase on the product title with CSS, but there are many non-uppercase words on the live site pages. Example https://main--airlessco--hlxsites.hlx.page/emea/de/products/hv4000luxe

Discussion:

The title is automatically set to uppercase for anything in a `<strong>` tag. We can remove this, and that would mean that the authors would need to uppercase the portions of the title that they want uppercase.

However, if we do that, then every page would need a Nav Title manually entered into the MetaData. The Nav Title is either:

* Metadata entry (priority)
* `<strong>` section of title - as is (not uppercase).

So if we remove the auto-casing, then curate the content to uppercase in source doc, we have to also add Nav Title information.

The only pages this is an issue on are the HVLP products, but on all languages.

Is correcting this important enough that we make the content changes to enter Nav Titles, and change the CSS?

**Comment by angellg1** [comment]
@bstopp would the Nav Title require entering the value in the page's meta data or in the product data spreadsheet file?
If it requires adding the Nav Title manually on every page then it can be leave as-is. If we can populate NavTitle within the product data spreadsheet then let's move forward with changing it and removing the uppercase class.

**Comment by bstopp** [comment]
Unfortunately, the Nav Title comes from the individual pages, that's the only supported source for page metadata. 

I don't mind going through and making the changes if that's the desired state.

**Comment by angellg1** [comment]
No, leave it as-is.

**Comment by tcameron-graco** [comment]
Is it possible to remove the upper-case setting using CSS lang pseudo-class or all non-English languages or only set to upper-case for English

**Comment by bstopp** [comment]
Let me check on this - i don't see why not.

**Comment by bstopp** [comment]
I had to touch the content on every page to change how the images were managed. This has been fixed.
