### ISSUE TITLE
Product Comparison Expansion

### ISSUE THREAD

**Issue by bstopp** [hlxsites/airlessco#161]
Concern:

> Live site only has 2 items in the "compare to" for this product in all languages, Ours has 3 https://main--airlessco--hlxsites.hlx.page/emea/nl/products/ts1750

Discussion:

So on the live site, the TS1750 is compared to the HSS9950 - but the table consolidates the Electric and Gas powered version of the HSS9950 into one column.

Our changes pull the product information from each product's data in the source sheet. So in order to compare, we have to have the HSS9950 Elect and Gas versions in their own column for the comparison table.

Will this be an issue?

**Comment by angellg1** [comment]
@bstopp this is not an issue
