### ISSUE TITLE
Missing hose on product image

### ISSUE THREAD

**Issue by bstopp** [hlxsites/airlessco#162]
Concern:

> This product image doesn't have a hose in it on the live site for any language except English - https://main--airlessco--hlxsites.hlx.page/emea/cz/products/hss9950electric

Discussion:

This may be due to that hose isn't available anywhere besides North America. Is having it in the product image an issue in other languages? If so, it should just be a content change.

**Comment by angellg1** [comment]
This is not an issue. The gun and hose photo can be used for all languages.
