### ISSUE TITLE
Mobile Breakpoints - Footer

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/airlessco#21]

**Comment by helms-charity** [comment]
Do I have the ability to push here? 
`09:41:04.881: [airlessco] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/issue-21_footer:issue-21_footer --set-upstream
remote: Permission to hlxsites/airlessco.git denied to venturewise.
fatal: unable to access 'https://github.com/hlxsites/airlessco.git/': The requested URL returned error: 403`

**Comment by dkuntze** [comment]
You have the same permissions as everyone else. Perhaps your certs are not attached to your profile.

**Comment by bstopp** [comment]
Fixed as per @venturewise
