### ISSUE TITLE
Set up 404 Page

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/airlessco#22]

**Comment by helms-charity** [comment]
Assigning myself as I got some details from @bstopp 

> There’s a global 404 - but maybe we can source the message from a placeholder. The 404 page also doesn’t load in the language-specific header/footer. If we can get that, that’d be awesome.


Live site shows blank page while trying to load some 3rd party search?
`Mixed Content: The page at 'https://www.airlessco.com/na/en/products/accessoriesss' was loaded over HTTPS, but requested an insecure frame 'http://www.searchvity.com/?dn=www.airlessco.com&pid=9POL6F2H4'. This request has been blocked; the content must be served over HTTPS.`

404.html page as of 2023-02-14T09:25:03-05:00 on Main does not have header/footer:
https://main--airlessco--hlxsites.hlx.page/emea/nl/products/ttt

**Comment by helms-charity** [comment]
will strive for something similar to this (crude mockup), where the 404 message is in the same language as the header/footer for each locale.

![image](https://user-images.githubusercontent.com/3883795/218785364-52353b1f-92fb-4764-bb96-ec0f51023e3e.png)
