### ISSUE TITLE
[fix] Support Styling

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/airlessco#57]
https://main--airlessco--hlxsites.hlx.page/emea/fr/support/

**Comment by helms-charity** [comment]
issue  #81 is a duplicate. I will close that one, but here is the screenshot that was linked there:
https://user-images.githubusercontent.com/2071728/215528470-67d17ab6-d81b-4b2f-b53e-e61fe270c0e6.png

**Comment by helms-charity** [comment]
Also adding to this ticket: 
Global style for link color and hover color fix.
