### ISSUE TITLE
Footer size too tall

### ISSUE THREAD

**Issue by lamontacrook** [hlxsites/airlessco#80]
Image on the left is Franklin and right is the site.

![image](https://user-images.githubusercontent.com/2071728/215526805-bc730a67-7f16-46f2-86d9-7545cf4e8f0a.png)

**Comment by helms-charity** [comment]
I think this will look better when my PR#77 is merged from the "issue-21" branch.
https://issue-21--airlessco--hlxsites.hlx.page/na/en/products/

**Comment by helms-charity** [comment]
I'm going to use this issue to also add space between the Products and Support lists, 
![2023-02-02_13-50-16](https://user-images.githubusercontent.com/3883795/216421784-0cfd20c5-ac6c-4a73-ba5f-bbf33918feb8.png)
