### ISSUE TITLE
Line Strippers Formatting

### ISSUE THREAD

**Issue by lamontacrook** [hlxsites/airlessco#82]
Layout on left is franklin.

![image](https://user-images.githubusercontent.com/2071728/215528998-d14337d1-ed3d-4713-9705-2b5fef0a2516.png)

**Comment by helms-charity** [comment]
@lamontacrook what's the URL for this? 
Is it https://www.airlessco.com/na/en/support/ ?

**Comment by helms-charity** [comment]
@lamontacrook actually I think you just have the wrong screenshot here, I found the support page ticket is https://github.com/hlxsites/airlessco/issues/81 .

**Comment by lamontacrook** [comment]
It looks like I posted the wrong screenshot.  Sorry.  I will close.
