### ISSUE TITLE
Product Accessories list

### ISSUE THREAD

**Issue by bstopp** [hlxsites/airlessco#91]
Need a better way to handle the list of accessories regardless of how short or long the list is.

**Comment by helms-charity** [comment]
https://www.airlessco.com/emea/en/products/hv3000comfort/ doesn't exist in US.
Compare with new prod page for same one, 
https://main--airlessco--hlxsites.hlx.page/emea/en/products/hv3000comfort

This one has all accessories
https://main--airlessco--hlxsites.hlx.page/emea/en/products/sl1250
but https://www.airlessco.com/na/en/products/sl1250/ has one fewer.

Just go with looks good for all conditions. Original flexbox was based off the NA/en and he didn't realize the diffs in other languages. 
Accessories block in the css.
