### ISSUE TITLE
Product Detail Images

### ISSUE THREAD

**Issue by bstopp** [hlxsites/airlessco#92]
Not all of the product detail pages have their images in the same order as the live site.

Is this an issue?

**Comment by helms-charity** [comment]
Adding example for clarity -- is this what you mean?
Live site: https://www.airlessco.com/na/en/products/mp455/
![image](https://user-images.githubusercontent.com/3883795/218762362-1ff0d18a-5305-45b5-8d28-32abe76c2fca.png)

Matching: EMEA English main: https://main--airlessco--hlxsites.hlx.page/emea/en/products/mp455

Not matching: NA English main: https://main--airlessco--hlxsites.hlx.page/na/en/products/mp455

**Comment by angellg1** [comment]
@bstopp  is there any logic that provides the sort order for images? I would say in the provided examples it is not an issue but I wouldn't want the Hose & Gun photo that currently is sorted at the end being the first image for a product. 
Is there control of sort order somewhere that we are able to adjust per product if we do need to make any change(s)?

**Comment by bstopp** [comment]
The order in the sheet is the order displayed on the page. I think whomever uploaded or curated the original product record simply put the images in the wrong order.

**Comment by bstopp** [comment]
This solution may be changing soon, before the go-live. I'll have more information in the Author Guide. And the change should resolve this issue.

**Comment by helms-charity** [comment]
By the way, when I was QA'ing on Friday, I did correct the order of the images so they matched the live site, but I don't know that I republished all the pages.

**Comment by bstopp** [comment]
This has been fixed via the updates to the Product image source as well. More info to follow in the Author guide on the management of the order.
